### Bienvenida a la API
GET https://porras-api-production.up.railway.app/
###
POST https://porras-api-production.up.railway.app/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1234"
}
###
GET https://porras-api-production.up.railway.app/dashboard
###
GET https://porras-api-production.up.railway.app/logout

